### ISSUE TITLE
WINE is NOT an emulator

### ISSUE THREAD

**Issue by michaeleldar** [PPPDUD/SUIT#1]
From the wiki
`then you can use an emulator such as WINE.`
From wikipedia (and the website)
`Wine (formerly a [recursive](https://en.wikipedia.org/wiki/Recursive_acronym) [backronym](https://en.wikipedia.org/wiki/Backronym) for Wine Is Not an [Emulator](https://en.wikipedia.org/wiki/Emulator), now just "Wine")`

**Comment by PPPDUD** [comment]
Well, then, what is Wine?

**Comment by michaeleldar** [comment]
A windows compatibility layer

**Comment by PPPDUD** [comment]
I see.
